var p=this;function q(a,b){var c=a.split("."),e=p;c[0]in e||!e.execScript||e.execScript("var "+c[0]);for(var d;c.length&&(d=c.shift());)c.length||void 0===b?e[d]?e=e[d]:e=e[d]={}:e[d]=b}
function r(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function t(a){return"string"==typeof a}var u="closure_uid_"+(1E9*Math.random()>>>0),aa=0;function v(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}
function w(a,b){function c(){}c.prototype=b.prototype;a.W=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.X=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};function x(){0!=ba&&(this[u]||(this[u]=++aa));this.b=this.b;this.l=this.l}var ba=0;x.prototype.b=!1;function y(a){y[" "](a);return a}y[" "]=function(){};var z=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function A(a,b){return a<b?-1:a>b?1:0};var B;a:{var C=p.navigator;if(C){var D=C.userAgent;if(D){B=D;break a}}B=""};function ca(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function da(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}function ea(a){for(var b in a)return!1;return!0};function E(a,b){this.type=a;this.l=this.w=b}E.prototype.A=function(){};var F="closure_listenable_"+(1E6*Math.random()|0),fa=0;function ga(a,b,c,e,d){this.listener=a;this.b=null;this.src=b;this.type=c;this.C=!!e;this.c=d;this.M=++fa;this.B=this.F=!1}function H(a){a.B=!0;a.listener=null;a.b=null;a.src=null;a.c=null};function I(a,b,c,e){return a||b?a?b?J(K(L,a.j,b.j,c,e)):a:J(K(L,{},b.j,c,e)):null}function K(a,b,c,e,d){e=e||0;d=d||0;var f={},g;for(g in b){var h=a(b[Number(g)],c[Number(g)-d]||null,e);h&&(f[g]=h)}for(g in c)(h=a(b[Number(g)+d]||null,c[Number(g)],e))&&(f[Number(g)+d]=h);return f}function J(a){ca(a,function(a){for(var c=0;c<a.length;++c);});return ea(a)?null:{j:a,g:ha(a),N:ia(a)}}
function ha(a){var b=Infinity,c=Infinity,e=-Infinity,d=-Infinity,f;for(f in a)Number(f)<c&&(c=Number(f)),Number(f)+1>d&&(d=Number(f)+1),0!=a[f].length&&(a[f][0]<b&&(b=a[f][0]),a[f][a[f].length-1]>e&&(e=a[f][a[f].length-1]));return b>=e||c>=d?null:{m:b,s:c,I:e,J:d}}function ia(a){for(var b in a)if(2!=a[b].length)return!1;return!0}
function ja(a,b){var c={},e;for(e in a.j)if(!(e<b.s||e>=b.J)){var d;d=a.j[e];var f=b.m,g=b.I;if(d){for(var h=[],k=!1,l=!1,n=0;n<d.length;++n){var m=d[n];!l&&m>=f&&(k?m<g?m>f&&(h.push(f),h.push(m)):(h.push(f),h.push(g)):h.push(m));l&&(m>g?k&&h.push(g):(m<g||m<=g&&k)&&h.push(m));l=m>=f&&m<g;if(m>=g)break;k=!k}d=0==h.length?null:h}else d=null;d&&(c[e]=d)}return J(c)}
function L(a,b,c){var e=c||0;if(null==a&&null==b)return null;if(null==a)return ka(b,function(a){return Number(a)+e});if(null==b)return a;if(2==a.length&&2==b.length)return la(a,b,e);for(var d=c=0,f=0,g=[],h=!0;;)if(c<a.length&&(d>=b.length||d<b.length&&a[c]<b[d]+e))0==c%2?(0==f&&(g.push(a[c]),h=!1),f++):(f--,0==f&&(g.push(a[c]),h=!1)),c++;else if(c<a.length&&d<b.length&&a[c]==b[d]+e)c%2==d%2&&(g.push(a[c]),h=!1,f=(c+1)%2+(d+1)%2),c++,d++;else if(d<b.length)0==d%2?(0==f&&(g.push(b[d]+e),h=!1),f++):
(f--,0==f&&(g.push(b[d]+e),h=!1)),d++;else break;return h?null:g}function la(a,b,c){return a||b?b?a?a[1]<b[0]+c?[a[0],a[1],b[0]+c,b[1]+c]:b[1]+c<a[0]?[b[0]+c,b[1]+c,a[0],a[1]]:[Math.min(a[0],b[0]+c),Math.max(a[1],b[1]+c)]:[b[0]+c,b[1]+c]:a:null};var M=Array.prototype,ma=M.indexOf?function(a,b,c){return M.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(t(a))return t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ka=M.map?function(a,b,c){return M.map.call(a,b,c)}:function(a,b,c){for(var e=a.length,d=Array(e),f=t(a)?a.split(""):a,g=0;g<e;g++)g in f&&(d[g]=b.call(c,f[g],g,a));return d};var na=-1!=B.indexOf("Opera")||-1!=B.indexOf("OPR"),N=-1!=B.indexOf("Trident")||-1!=B.indexOf("MSIE"),oa=-1!=B.indexOf("Edge"),O=-1!=B.indexOf("Gecko")&&!(-1!=B.toLowerCase().indexOf("webkit")&&-1==B.indexOf("Edge"))&&!(-1!=B.indexOf("Trident")||-1!=B.indexOf("MSIE"))&&-1==B.indexOf("Edge"),P=-1!=B.toLowerCase().indexOf("webkit")&&-1==B.indexOf("Edge");
function pa(){var a=B;if(O)return/rv\:([^\);]+)(\)|;)/.exec(a);if(oa)return/Edge\/([\d\.]+)/.exec(a);if(N)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(P)return/WebKit\/(\S+)/.exec(a)}function qa(){var a=p.document;return a?a.documentMode:void 0}var ra=function(){if(na&&p.opera){var a=p.opera.version;return"function"==r(a)?a():a}var a="",b=pa();b&&(a=b?b[1]:"");return N&&(b=qa(),b>parseFloat(a))?String(b):a}(),sa={};
function Q(a){var b;if(!(b=sa[a])){b=0;for(var c=z(String(ra)).split("."),e=z(String(a)).split("."),d=Math.max(c.length,e.length),f=0;0==b&&f<d;f++){var g=c[f]||"",h=e[f]||"",k=RegExp("(\\d*)(\\D*)","g"),l=RegExp("(\\d*)(\\D*)","g");do{var n=k.exec(g)||["","",""],m=l.exec(h)||["","",""];if(0==n[0].length&&0==m[0].length)break;b=A(0==n[1].length?0:parseInt(n[1],10),0==m[1].length?0:parseInt(m[1],10))||A(0==n[2].length,0==m[2].length)||A(n[2],m[2])}while(0==b)}b=sa[a]=0<=b}return b}
var ta=p.document,ua=ta&&N?qa()||("CSS1Compat"==ta.compatMode?parseInt(ra,10):5):void 0;!O&&!N||N&&9<=ua||O&&Q("1.9.1");N&&Q("9");function R(a){this.src=a;this.b={};this.c=0}R.prototype.hasListener=function(a,b){var c=void 0!==a,e=c?a.toString():"",d=void 0!==b;return da(this.b,function(a){for(var g=0;g<a.length;++g)if(!(c&&a[g].type!=e||d&&a[g].C!=b))return!0;return!1})};var va=!N||9<=ua,wa=N&&!Q("9");!P||Q("528");O&&Q("1.9b")||N&&Q("8")||na&&Q("9.5")||P&&Q("528");O&&!Q("8")||N&&Q("9");function S(a,b){E.call(this,a?a.type:"");this.l=this.w=null;this.button=this.clientY=this.clientX=this.c=this.b=0;this.i=null;a&&this.G(a,b)}w(S,E);
S.prototype.G=function(a,b){this.type=a.type;this.w=a.target||a.srcElement;this.l=b;var c=a.relatedTarget;if(c&&O)try{y(c.nodeName)}catch(e){}this.b=P||void 0!==a.offsetX?a.offsetX:a.layerX;this.c=P||void 0!==a.offsetY?a.offsetY:a.layerY;this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.button=a.button;this.i=a;a.defaultPrevented&&this.A()};
S.prototype.A=function(){S.W.A.call(this);var a=this.i;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,wa)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var T="closure_lm_"+(1E6*Math.random()|0),U={},xa=0;
function ya(a,b,c,e,d){if("array"==r(b)){for(var f=0;f<b.length;f++)ya(a,b[f],c,e,d);return null}c=za(c);if(a&&a[F])a=V(a,b,c,e,d);else{f=c;if(!b)throw Error("Invalid event type");c=!!e;var g=W(a);g||(a[T]=g=new R(a));var h=g,k=b.toString(),g=h.b[k];g||(g=h.b[k]=[],h.c++);var l;b:{for(l=0;l<g.length;++l){var n=g[l];if(!n.B&&n.listener==f&&n.C==!!e&&n.c==d)break b}l=-1}-1<l?(e=g[l],e.F=!1):(e=new ga(f,h.src,k,!!e,d),e.F=!1,g.push(e));if(!e.b){d=Aa();e.b=d;d.src=a;d.listener=e;if(a.addEventListener)a.addEventListener(b.toString(),
d,c);else if(a.attachEvent)a.attachEvent(Ba(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");xa++}a=e}return a}function Aa(){var a=Ca,b=va?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function Ba(a){return a in U?U[a]:U[a]="on"+a}function Da(a,b,c,e){var d=!0;if(a=W(a))if(b=a.b[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.C==c&&!f.B&&(f=Ea(f,e),d=d&&!1!==f)}return d}
function Ea(a,b){var c=a.listener,e=a.c||a.src;if(a.F&&"number"!=typeof a&&a&&!a.B){var d=a.src;if(d&&d[F])d.ca(a);else{var f=a.type,g=a.b;d.removeEventListener?d.removeEventListener(f,g,a.C):d.detachEvent&&d.detachEvent(Ba(f),g);xa--;if(f=W(d)){var g=a.type,h;if(h=g in f.b){h=f.b[g];var k=ma(h,a),l;(l=0<=k)&&M.splice.call(h,k,1);h=l}h&&(H(a),0==f.b[g].length&&(delete f.b[g],f.c--));0==f.c&&(f.src=null,d[T]=null)}else H(a)}}return c.call(e,b)}
function Ca(a,b){if(a.B)return!0;if(!va){var c;if(!(c=b))a:{c=["window","event"];for(var e=p,d;d=c.shift();)if(null!=e[d])e=e[d];else{c=null;break a}c=e}d=c;c=new S(d,this);e=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var f=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==d.returnValue)d.returnValue=!0}d=[];for(f=c.l;f;f=f.parentNode)d.push(f);for(var f=a.type,h=d.length-1;0<=h;h--){c.l=d[h];var k=Da(d[h],f,!0,c),e=e&&k}for(h=0;h<d.length;h++)c.l=d[h],k=Da(d[h],f,!1,c),
e=e&&k}return e}return Ea(a,new S(b,this))}function W(a){a=a[T];return a instanceof R?a:null}var X="__closure_events_fn_"+(1E9*Math.random()>>>0);function za(a){if("function"==r(a))return a;a[X]||(a[X]=function(b){return a.handleEvent(b)});return a[X]};function Y(a){x.call(this);this.c=a;this.i={}}w(Y,x);var Fa=[];function V(a,b,c,e,d){"array"!=r(c)&&(c&&(Fa[0]=c.toString()),c=Fa);for(var f=0;f<c.length;f++){var g=ya(b,c[f],e||a.handleEvent,d||!1,a.c||a);if(!g)break;a.i[g.M]=g}return a}Y.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Ga(a){var b=document;return t(a)?b.getElementById(a):a};var Z={G:function(){var a=new Y,b,c={};b=Math.floor(10);for(var e=-b;e<=b;++e){var d=Math.round(Math.sqrt(100-e*e));0<d&&(c[e]=[-d,d])}b=J(c);c=Ga("single-canvas");b={cursor:b,Z:a,canvas:c,Y:Ga("dbg-canvas"),h:J({})};Z.ba=b;V(a,c,"mousemove",v(Z.P,b),void 0);V(a,document,"mousedown",v(Z.O,b),void 0);V(a,document,"mouseup",v(Z.R,b),void 0);V(a,c,"touchstart",v(Z.U,b),void 0);V(a,c,"touchmove",v(Z.T,b),void 0);V(a,c,"touchend",v(Z.S,b),void 0);Z.H(b)}};
Z.V=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)};Z.H=function(a){Z.V(v(Z.H,a));Z.L(a)};Z.O=function(a,b){a.D=!0;b.w==a.canvas&&(a.a=I(null,a.cursor,b.b-(a.a&&a.a.g&&a.a.g.m||0),b.c-(a.a&&a.a.g&&a.a.g.s||0)),a.v=a.a,a.f=[[b.b,b.c]],a.u=[b.b,b.c])};Z.P=function(a,b){b.i.buttons&&(a.f.push([b.b,b.c]),a.o=[b.b,b.c])};Z.R=function(a){a.D=!1;a.v=a.a;a.h=I(a.h,a.a);a.a=null;a.u=null;a.f=[]};
Z.aa=function(a,b){console.log(b.i.button);a.D=!0;b.w==a.canvas&&(a.a=I(null,a.cursor,b.b-(a.a&&a.a.g&&a.a.g.m||0),b.c-(a.a&&a.a.g&&a.a.g.s||0)),a.v=a.a,a.f=[b.b,b.c])};Z.$=function(a){a.D=!1;a.h=I(a.h,a.a);a.v=a.a;a.a=null;a.u=null;a.f=[]};Z.U=function(a,b){b.A();a.f=[];a.a&&(a.h=I(a.h,a.a));var c=b.i.touches,e=a.a;if(!(1<c.length)){for(var d=0;d<c.length;++d){var f=c[d],g=Math.floor(f.clientX),f=Math.floor(f.clientY);a.f=[[g,f]];a.u=[g,f];a.o=[g,f]}a.a=e;a.v=a.a}};
Z.T=function(a,b){var c=[Math.round(b.i.touches[0].clientX),Math.round(b.i.touches[0].clientY)];a.f.push(c);a.u=c;a.o=c};Z.S=function(a,b){b.A();a.D=!1;a.h=I(a.h,a.a);a.a=null;a.v=a.a};
Z.L=function(a){var b,c;if(a.o){var e=I(a.a,a.cursor,a.o[0],a.o[1]);c=e.g;var d=I(a.h,e);a.o=null;b=ja(d,c)}else{if(!a.f||0==a.f.length)return;e=Z.K(a);a.u=a.f[a.f.length-1];a.f=[];if(!e)return;c=e.g;e=I(a.a,e);d=I(a.h,e);b=ja(d,c)}a.a=e;a=a.canvas.getContext("2d");e=c.I-c.m;d=a.createImageData(e,c.J-c.s);b=b.j;for(var f in b)for(var g=Number(f)-c.s,h=b[Number(f)],k=0;k<h.length;k+=2)for(var l=h[k]-c.m;l<h[k+1]-c.m;++l)d.data[4*(e*g+l)+0]=0,d.data[4*(e*g+l)+1]=0,d.data[4*(e*g+l)+2]=0,d.data[4*(e*
g+l)+3]=255;a.putImageData(d,c.m,c.s)};
Z.K=function(a){var b=null,c=a.u;c||(c=a.f[0]);for(var e=0;e<a.f.length;++e){var d,f=a.cursor;d=f.N?la:L;var g=c[0],h=c[1],c=a.f[e][0],k=a.f[e][1],l={},n=g,m=h,G=f.j;if(g==c&&h==k)d=I(null,f,g,h);else{if(Math.abs(c-g)>Math.abs(k-h))if(g<c)for(f=1,g=(k-h)/(c-g);n<=c;)l=K(d,l,G,Math.round(n),Math.round(m)),n+=f,m+=g;else for(f=-1,g=-(k-h)/(c-g);n>=c;)l=K(d,l,G,Math.round(n),Math.round(m)),n+=f,m+=g;else if(h<k)for(f=(c-g)/(k-h),g=1;m<=k;)l=K(d,l,G,Math.round(n),Math.round(m)),n+=f,m+=g;else for(f=-(c-
g)/(k-h),g=-1;m>=k;)l=K(d,l,G,Math.round(n),Math.round(m)),n+=f,m+=g;d=J(l)}b=I(b,d);c=a.f[e];for(d=0;1E6>d;++d);}return b};q("fixel.jspaint.SquarePaint",Z);q("fixel.jspaint.SquarePaint.init",Z.G);
