// This file was autogenerated by ./closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../src/fixel/canvas.js', ['fixel.canvas.Canvas'], [], false);
goog.addDependency('../../src/fixel/color.js', ['fixel.color', 'fixel.color.Color'], ['goog.asserts'], false);
goog.addDependency('../../src/fixel/jspaint/renderer.js', ['fixel.jspaint.Context2dLike', 'fixel.jspaint.renderer'], ['fixel.jspaint.Scene', 'fixel.mask.Mask', 'fixel.rectangle.Rectangle'], false);
goog.addDependency('../../src/fixel/jspaint/scene.js', ['fixel.jspaint.Layer', 'fixel.jspaint.Scene', 'fixel.jspaint.SceneDiff'], ['fixel.color.Color', 'fixel.mask.Mask', 'fixel.rectangle.Rectangle'], false);
goog.addDependency('../../src/fixel/jspaint/square-paint.js', ['fixel.jspaint.SquarePaint'], ['fixel.jspaint.renderer', 'fixel.jspaint.tools.Drag', 'fixel.jspaint.tools.Freeform', 'fixel.jspaint.tools.Line', 'fixel.point', 'fixel.rectangle', 'fixel.shapes', 'goog.dom', 'goog.events.Event', 'goog.events.EventHandler', 'goog.events.EventType'], false);
goog.addDependency('../../src/fixel/jspaint/tool.js', ['fixel.jspaint.Tool'], ['fixel.jspaint.Scene', 'fixel.mask.Mask', 'fixel.point.Point'], false);
goog.addDependency('../../src/fixel/jspaint/tools/drag.js', ['fixel.jspaint.tools.Drag'], ['fixel.color', 'fixel.color.Color', 'fixel.jspaint.Tool', 'fixel.mask', 'fixel.mask.Mask', 'fixel.point', 'fixel.point.Point'], false);
goog.addDependency('../../src/fixel/jspaint/tools/freeform.js', ['fixel.jspaint.tools.Freeform'], ['fixel.color.Color', 'fixel.jspaint.Tool', 'fixel.mask', 'fixel.mask.Mask', 'fixel.point.Point'], false);
goog.addDependency('../../src/fixel/jspaint/tools/line.js', ['fixel.jspaint.tools.Line'], ['fixel.color.Color', 'fixel.jspaint.Tool', 'fixel.mask', 'fixel.mask.Mask', 'fixel.point.Point', 'fixel.rectangle'], false);
goog.addDependency('../../src/fixel/mask.js', ['fixel.mask', 'fixel.mask.Alternations', 'fixel.mask.Mask'], ['fixel.point', 'fixel.rectangle', 'fixel.rectangle.Rectangle', 'goog.array', 'goog.asserts', 'goog.object'], false);
goog.addDependency('../../src/fixel/point.js', ['fixel.point', 'fixel.point.Point'], [], false);
goog.addDependency('../../src/fixel/rectangle.js', ['fixel.rectangle', 'fixel.rectangle.Rectangle'], [], false);
goog.addDependency('../../src/fixel/shapes.js', ['fixel.shapes'], ['fixel.mask', 'fixel.rectangle'], false);
