// This file was autogenerated by ./closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../src/jspaint/square-paint.js', ['jspaint.SquarePaint'], ['goog.dom', 'goog.events.EventHandler', 'goog.events.EventType', 'mask'], false);
goog.addDependency('../../src/mask/mask-line-test.js', ['mask.MaskLineTest'], ['mask.MaskLine'], false);
goog.addDependency('../../src/mask/mask-line.js', ['mask.MaskLine', 'mask.MaskLine.Alternations'], ['goog.array'], false);
goog.addDependency('../../src/mask/mask-test.js', ['mask.MaskTest'], ['goog.asserts', 'goog.object', 'mask', 'mask.Mask', 'mask.MaskLineTest'], false);
goog.addDependency('../../src/mask/mask.js', ['mask', 'mask.Mask', 'mask.Rectangle'], ['mask.MaskLine', 'mask.MaskLine.Alternations'], false);
