// This file was autogenerated by ./closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../src/fixel/canvas.js', ['fixel.canvas.Canvas'], [], false);
goog.addDependency('../../src/fixel/color.js', ['fixel.Color'], ['goog.asserts'], false);
goog.addDependency('../../src/fixel/jspaint/renderer.js', ['fixel.jspaint.Context2dLike', 'fixel.jspaint.renderer'], ['fixel.jspaint.Scene', 'fixel.rectangle.Rectangle'], false);
goog.addDependency('../../src/fixel/jspaint/scene.js', ['fixel.jspaint.Layer', 'fixel.jspaint.Scene', 'fixel.jspaint.SceneDiff', 'fixel.jspaint.scene'], ['fixel.Color', 'fixel.mask.Mask'], false);
goog.addDependency('../../src/fixel/jspaint/square-paint.js', ['fixel.jspaint.SquarePaint'], ['fixel.jspaint.renderer', 'fixel.jspaint.tools.Freeform', 'fixel.shapes', 'goog.dom', 'goog.events.Event', 'goog.events.EventHandler', 'goog.events.EventType'], false);
goog.addDependency('../../src/fixel/jspaint/tool.js', ['fixel.jspaint.Tool'], ['fixel.Point', 'fixel.jspaint.Scene', 'fixel.mask.Mask'], false);
goog.addDependency('../../src/fixel/jspaint/tools/freeform.js', ['fixel.jspaint.tools.Freeform'], ['fixel.Color', 'fixel.Point', 'fixel.jspaint.Tool', 'fixel.jspaint.scene', 'fixel.mask', 'fixel.mask.Mask'], false);
goog.addDependency('../../src/fixel/mask-test.js', ['fixel.mask.MaskTest'], [], false);
goog.addDependency('../../src/fixel/mask.js', ['fixel.mask', 'fixel.mask.Alternations', 'fixel.mask.Mask'], ['fixel.rectangle', 'fixel.rectangle.Rectangle', 'goog.array', 'goog.asserts', 'goog.object'], false);
goog.addDependency('../../src/fixel/point.js', ['fixel.Point'], [], false);
goog.addDependency('../../src/fixel/rectangle.js', ['fixel.rectangle', 'fixel.rectangle.Rectangle'], [], false);
goog.addDependency('../../src/fixel/shapes.js', ['fixel.shapes'], ['fixel.mask'], false);
